spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/catalog
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL95Dialect



