spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/inventory
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8084/eureka/




