spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/catalog
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate




