server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    catalog-service:
      path: /catalog/**
      serviceId: catalog-service
      stripPrefix: false
      sensitiveHeaders:
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      stripPrefix: false
      sensitiveHeaders:
    manager-service:
      path: /manager/**
      serviceId: manager-service
      stripPrefix: false
      sensitiveHeaders:

